version: '3'
services:
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
          - "80:8000"
        volumes:
          - ./:/app
          - ./config/nginx:/etc/nginx/conf.d
        depends_on:
          - web
    web:
        environment:
          - DJANGO_SUPERUSER_PASSWORD=www12345
          - DJANGO_SUPERUSER_ADMIN=admin
          - INSHORT_ENV=docker
        container_name: django
        build: ./
        volumes:
        - ./:/app
        depends_on:
        - db
        command: ["./start.sh"]
        expose:
          - "8000"

    db:
        container_name: mysql
        image: mysql:5.7 
        ports:
          - '3306:3306'
        environment:
          MYSQL_DATABASE: 'inshort'
          MYSQL_USER: 'inshort'
          MYSQL_PASSWORD: 'j3qq4h7h2v'
          MYSQL_ROOT_PASSWORD: 'password'
