version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - "443:443"
    volumes:
      - ./:/app
      - ./config/nginx:/etc/nginx/conf.d
      - ./config/data/certbot/conf:/etc/letsencrypt
      - ./config/data/certbot/www:/var/www/certbot
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./config/data/certbot/conf:/etc/letsencrypt
      - ./config/data/certbot/www:/var/www/certbot
      
  web:
    environment:
      - DJANGO_SUPERUSER_PASSWORD=www12345
      - DJANGO_SUPERUSER_ADMIN=admin
      - INSHORT_ENV=docker
    container_name: django
    build: ./
    volumes:
      - ./:/app
    depends_on:
      - db
    command: ["./start.sh"]
    expose:
      - "8000"

  db:
    container_name: mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_configBASE: "inshort"
      MYSQL_USER: "inshort"
      MYSQL_PASSWORD: "j3qq4h7h2v"
      MYSQL_ROOT_PASSWORD: "password"
