version: '2'
services:
    web:
        build: ./
        command: python ./manage.py runserver 0.0.0.0:8000
        ports:
        - 8000:8000
        volumes:
        - ./:/app
        depends_on:
        - db
    db:
        image: postgres
        environment:
          - POSTGRES_DB=postgres
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
