version: '3'
services:
    web:
        environment:
          - DJANGO_SUPERUSER_PASSWORD=www12345
          - DJANGO_SUPERUSER_ADMIN=admin
        build: ./
        ports:
        - 8000:8000
        volumes:
        - ./:/app
        depends_on:
        - db
        command: ["./start.sh"]

    db:
        image: postgres
        environment:
          - POSTGRES_DB=postgres
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
