# Generated by Django 3.0.4 on 2020-04-28 19:01

import custom_urls.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUrl',
            fields=[
                ('long_url', models.URLField(max_length=2000)),
                ('short_url', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('expiration_date', models.DateTimeField(default=custom_urls.models.get_default_expire_date, null=True)),
                ('is_active', models.BooleanField()),
                ('owner', models.ForeignKey(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.Session')),
            ],
            options={
                'ordering': ['owner', 'expiration_date'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('visitor_ip', models.GenericIPAddressField(null=True)),
                ('visitor_location', models.CharField(max_length=200, null=True)),
                ('custom_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_urls.CustomUrl')),
            ],
            options={
                'ordering': ['custom_url__owner', 'datetime'],
            },
        ),
    ]
