# Generated by Django 3.0.5 on 2020-05-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_urls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customurl',
            name='short_url',
            field=models.CharField(max_length=20),
        ),
    ]
