# Generated by Django 3.0.5 on 2020-04-20 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_urls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customurl',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customurl',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitshistory',
            name='visitor_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
