# Generated by Django 3.0.5 on 2020-04-26 14:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('custom_urls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customurl',
            old_name='source_url',
            new_name='long_url',
        ),
        migrations.AlterField(
            model_name='customurl',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 26, 14, 28, 37, 654776, tzinfo=utc), null=True),
        ),
    ]
