# Generated by Django 3.0.5 on 2020-06-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_urls', '0002_auto_20200602_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customurl',
            name='short_url',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
