# Generated by Django 2.2.12 on 2020-04-26 23:53

import custom_urls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_urls', '0002_auto_20200426_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customurl',
            name='expiration_date',
            field=models.DateTimeField(default=custom_urls.models.get_default_expire_date, null=True),
        ),
    ]
