# Generated by Django 3.0.5 on 2020-04-20 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_urls', '0003_auto_20200420_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customurl',
            name='owner',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='visitshistory',
            name='custom_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_urls.CustomUrl'),
        ),
    ]
