# Generated by Django 3.0.5 on 2020-04-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_urls', '0003_auto_20200426_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='customurl',
            name='is_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
