# Generated by Django 3.0.5 on 2020-04-26 16:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('custom_urls', '0003_auto_20200426_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customurl',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 26, 16, 43, 3, 821579, tzinfo=utc), null=True),
        ),
    ]
