# Generated by Django 3.0.5 on 2020-04-29 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_urls', '0004_customurl_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customurl',
            options={'ordering': ['active', 'owner', 'expiration_date']},
        ),
        migrations.RenameField(
            model_name='customurl',
            old_name='is_active',
            new_name='active',
        ),
    ]
