# Generated by Django 3.0.5 on 2020-04-26 20:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('custom_urls', '0004_auto_20200426_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customurl',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 26, 20, 12, 49, 6209, tzinfo=utc), null=True),
        ),
    ]
