# Generated by Django 3.0.5 on 2020-04-21 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_urls', '0004_auto_20200420_2230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customurl',
            old_name='source_url',
            new_name='destination_url',
        ),
        migrations.RenameField(
            model_name='customurl',
            old_name='inshort_url',
            new_name='short_url',
        ),
        migrations.AddField(
            model_name='visitshistory',
            name='visitor_location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customurl',
            name='expiration_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='visitshistory',
            name='custom_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_urls.CustomUrl'),
        ),
        migrations.AlterField(
            model_name='visitshistory',
            name='visitor_ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
