# Generated by Django 3.0.5 on 2020-04-29 23:00

import custom_urls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_urls', '0005_auto_20200429_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customurl',
            name='expiration_date',
            field=models.DateTimeField(default=custom_urls.models.get_expire_date, null=True),
        ),
    ]
