# Generated by Django 3.0.5 on 2020-04-21 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('custom_urls', '0006_auto_20200421_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customurl',
            name='owner',
            field=models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customurl',
            name='short_url',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='custom_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_urls.CustomUrl'),
        ),
    ]
