# Generated by Django 3.0.5 on 2020-04-25 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('custom_urls', '0011_auto_20200423_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customurl',
            old_name='destination_url',
            new_name='source_url',
        ),
        migrations.AddField(
            model_name='customurl',
            name='session',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.Session'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='custom_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_urls.CustomUrl'),
        ),
    ]
