# Generated by Django 3.0.5 on 2020-04-25 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_urls', '0013_auto_20200425_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customurl',
            name='id',
        ),
        migrations.AlterField(
            model_name='customurl',
            name='short_url',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='custom_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_urls.CustomUrl'),
        ),
    ]
