# Generated by Django 3.0.5 on 2020-04-26 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('custom_urls', '0015_auto_20200425_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customurl',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.Session'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='custom_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_urls.CustomUrl'),
        ),
    ]
